<script>
  export let date;
</script>

<table class="table font-monospace">
  <thead>
    <tr>
      <td>function</td>
      <td>return</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>d.getUTCDate();</td>
      <td>{date.getUTCDate()}</td>
    </tr>
    <tr>
      <td>d.getUTCDay();</td>
      <td>{date.getUTCDay()}</td>
    </tr>
    <tr>
      <td>d.getUTCFullYear();</td>
      <td>{date.getUTCFullYear()}</td>
    </tr>
    <tr>
      <td>d.getUTCHours();</td>
      <td>{date.getUTCHours()}</td>
    </tr>
    <tr>
      <td>d.getUTCMilliseconds();</td>
      <td>{date.getUTCMilliseconds()}</td>
    </tr>
    <tr>
      <td>d.getUTCMinutes();</td>
      <td>{date.getUTCMinutes()}</td>
    </tr>
    <tr>
      <td>d.getUTCMonth();</td>
      <td>{date.getUTCMonth()}</td>
    </tr>
    <tr>
      <td>d.getUTCSeconds();</td>
      <td>{date.getUTCSeconds()}</td>
    </tr>
  </tbody>
</table>
