<script>
  export let date;
</script>

<table class="table font-monospace">
  <thead>
    <tr>
      <td>function</td>
      <td>return</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>d.getDate();</td>
      <td>{date.getDate()}</td>
    </tr>
    <tr>
      <td>d.getDay();</td>
      <td>{date.getDay()}</td>
    </tr>
    <tr>
      <td>d.getFullYear();</td>
      <td>{date.getFullYear()}</td>
    </tr>
    <tr>
      <td>d.getHours();</td>
      <td>{date.getHours()}</td>
    </tr>
    <tr>
      <td>d.getMilliseconds();</td>
      <td>{date.getMilliseconds()}</td>
    </tr>
    <tr>
      <td>d.getMinutes();</td>
      <td>{date.getMinutes()}</td>
    </tr>
    <tr>
      <td>d.getMonth();</td>
      <td>{date.getMonth()}</td>
    </tr>
    <tr>
      <td>d.getSeconds();</td>
      <td>{date.getSeconds()}</td>
    </tr>
    <tr>
      <td>d.getTime();</td>
      <td>{date.getTime()}</td>
    </tr>
  </tbody>
</table>
